# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruck}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Lieber"]
  s.date = %q{2010-06-26}
  s.description = %q{      Ruck uses continuations and a simple scheduler to ensure "shreds"
      (threads in Ruck) are woken at precisely the right time according
      to its virtual clock. Schedulers can map virtual time to samples
      in a WAV file, real time, time in a MIDI file, or anything else
      by overriding "sim_to" in the Shreduler class.
      
      A small library of useful unit generators and plenty of examples
      are provided. See the README or the web page for details.
}
  s.email = %q{tom@alltom.com}
  s.executables = ["ruck_glapp", "ruck_midi", "ruck_sleep", "ruck_ugen"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "bin/ruck_glapp",
     "bin/ruck_midi",
     "bin/ruck_sleep",
     "bin/ruck_ugen",
     "examples/glapp/ex01.rb",
     "examples/glapp/ex02.rb",
     "examples/glapp/ex03.rb",
     "examples/midi/ex01.rb",
     "examples/midi/ex02.rb",
     "examples/ugen/ex01.rb",
     "examples/ugen/ex02.rb",
     "examples/ugen/ex03.rb",
     "examples/ugen/ex04.rb",
     "examples/ugen/ex05.rb",
     "examples/ugen/ex06.rb",
     "examples/ugen/ex07.rb",
     "examples/ugen/ex08.rb",
     "examples/ugen/ex09.rb",
     "examples/ugen/ex10.rb",
     "examples/ugen/ex11.rb",
     "examples/ugen/ex12.rb",
     "lib/ruck.rb",
     "lib/ruck/bench.rb",
     "lib/ruck/misc/linkage.rb",
     "lib/ruck/misc/riff.rb",
     "lib/ruck/shreduling.rb",
     "lib/ruck/ugen.rb",
     "lib/ruck/ugen/basic.rb",
     "lib/ruck/ugen/oscillators.rb",
     "lib/ruck/ugen/time_helpers.rb",
     "lib/ruck/ugen/ugen.rb",
     "lib/ruck/ugen/wav.rb",
     "ruck.gemspec"
  ]
  s.homepage = %q{http://github.com/alltom/ruck}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{strong timing for Ruby: cooperative threads on a virtual clock}
  s.test_files = [
    "examples/glapp/ex01.rb",
     "examples/glapp/ex02.rb",
     "examples/glapp/ex03.rb",
     "examples/midi/ex01.rb",
     "examples/midi/ex02.rb",
     "examples/ugen/ex01.rb",
     "examples/ugen/ex02.rb",
     "examples/ugen/ex03.rb",
     "examples/ugen/ex04.rb",
     "examples/ugen/ex05.rb",
     "examples/ugen/ex06.rb",
     "examples/ugen/ex07.rb",
     "examples/ugen/ex08.rb",
     "examples/ugen/ex09.rb",
     "examples/ugen/ex10.rb",
     "examples/ugen/ex11.rb",
     "examples/ugen/ex12.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

