# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruck}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Lieber"]
  s.date = %q{2009-11-15}
  s.description = %q{strong timing for Ruby: cooperative threads on a virtual clock}
  s.email = %q{tom@alltom.com}
  s.executables = ["ruck_midi", "ruck_ugen"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "VERSION",
     "bin/ruck_midi",
     "bin/ruck_ugen",
     "examples/midi/ex01.rb",
     "examples/ugen/ex01.rb",
     "examples/ugen/ex02.rb",
     "examples/ugen/ex03.rb",
     "examples/ugen/ex04.rb",
     "examples/ugen/ex05.rb",
     "examples/ugen/ex06.rb",
     "examples/ugen/ex07.rb",
     "examples/ugen/ex08.rb",
     "examples/ugen/ex09.rb",
     "examples/ugen/ex10.rb",
     "examples/ugen/ex11.rb",
     "examples/ugen/ex12.rb",
     "lib/bench.rb",
     "lib/misc/linkage.rb",
     "lib/misc/metaid.rb",
     "lib/misc/pcm_time_helpers.rb",
     "lib/misc/riff.rb",
     "lib/misc/wavparse.rb",
     "lib/ruck.rb",
     "lib/shreduling.rb",
     "lib/ugen/general.rb",
     "lib/ugen/oscillators.rb",
     "lib/ugen/wav.rb"
  ]
  s.homepage = %q{http://github.com/alltom/ruck}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{strong timing for Ruby: cooperative threads on a virtual clock}
  s.test_files = [
    "examples/midi/ex01.rb",
     "examples/ugen/ex01.rb",
     "examples/ugen/ex02.rb",
     "examples/ugen/ex03.rb",
     "examples/ugen/ex04.rb",
     "examples/ugen/ex05.rb",
     "examples/ugen/ex06.rb",
     "examples/ugen/ex07.rb",
     "examples/ugen/ex08.rb",
     "examples/ugen/ex09.rb",
     "examples/ugen/ex10.rb",
     "examples/ugen/ex11.rb",
     "examples/ugen/ex12.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

